version: '2.1'

volumes:
  mysql:
    driver: local

services:

  php:
    image: php:7.2-lumen
    build:
      context: docker
      dockerfile: Dockerfile
    restart: always
    volumes:
    - .:/var/www/html
    - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
    - .env

  mysql:
    image: mysql:5.7
    mem_reservation: 200m
    mem_limit: 300m
    memswap_limit: 400m
    cpu_shares: 104
    restart: always
    env_file:
    - .env
    volumes:
    - mysql:/var/lib/mysql
    healthcheck:
      test: 'mysql -u $MYSQL_USER -p$MYSQL_PASSWORD --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 3s
      retries: 15
    ports:
    - ${MYSQL_PORT}:3306

  nginx:
    image: nginx:stable-alpine
    mem_reservation: 50m
    mem_limit: 100m
    memswap_limit: 200m
    cpu_shares: 104
    restart: always
    volumes:
    - .:/usr/share/nginx/html/
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - php
    ports:
    - ${HTTP_PORT}:80